export const users = [
  {
    id: 1,
    firstName: "Jane",
    lastName: "Wilkins",
    email: "jane.wilkins@gmail.com",
    address: {
      street: "Main Street",
      city: "Ambleside",
      postcode: "LA22 9BU",
      country: "United Kingdom",
    },
    isActive: false,
    cloudinary_id: "",
    userBio: "hello I'm Jane, i like food",
  },
  {
    id: 2,
    firstName: "Dennis",
    lastName: "Thompson",
    email: "dennis.thompson@gmail.com",
    address: {
      street: "Newlands Meadow",
      city: "High Wycombe",
      postcode: "HP11 2BZ",
      country: "United Kingdom",
    },
    isActive: true,
    cloudinary_id: "",
    userBio: "hello I'm Dennis, i like drink",
  },
];

export const items = [
  {
    itemId: 1,
    userId: 1,
    category: ["fruit", "vegetable"],
    itemName: "apple",
    itemDescription: "i have 5 red apples to give",
    useByDate: 21 / 2 / 22,
    dateAdded: 18 / 2 / 22,
    quantity: 5,
    cloudinary_id: "",
    isReserved: false,
    availablity: true,
    timeslot: ["9am-10am", "11am-12pm", "1pm-2pm"],
  },
  {
    itemId: 2,
    userId: 1,
    category: ["fruit", "vegetable"],
    itemName: "carrot",
    itemDescription: "i have 10kg of carrots to give",
    useByDate: 25 / 2 / 22,
    dateAdded: 18 / 2 / 22,
    quantity: 1,
    cloudinary_id: "",
    isReserved: true,
    availablity: false,
    timeslot: ["9am-10am", "11am-12pm", "1pm-2pm"],
  },
];
