export const users = [
	{
		full_name: "Jane Wilkins",
		email: "jane.wilkins@gmail.com",
		address: "Main Street, LA22 9BU, Ambleside, United Kingdom",
		is_active: false,
		cloudinary_id: "",
		avatar:
			"https://cdn.vox-cdn.com/thumbor/00awoM5IS2kFITs9546UyMSePBY=/0x0:2370x1574/1200x800/filters:focal(996x598:1374x976)/cdn.vox-cdn.com/uploads/chorus_image/image/69715362/Screen_Shot_2020_07_21_at_9.38.25_AM.0.png",
		user_bio: "hello I'm Jane, i like food",
	},
	{
		full_name: "Dennis Thompson",
		email: "dennis.thompson@gmail.com",
		address: "Newlands Meadow, HP11 2BZ, High Wycombe, United Kingdom",
		is_active: true,
		cloudinary_id: "",
		avatar:
			"https://cdn.vox-cdn.com/thumbor/00awoM5IS2kFITs9546UyMSePBY=/0x0:2370x1574/1200x800/filters:focal(996x598:1374x976)/cdn.vox-cdn.com/uploads/chorus_image/image/69715362/Screen_Shot_2020_07_21_at_9.38.25_AM.0.png",
		user_bio: "hello I'm Dennis, i like drink",
	},
];

export const items = [
	{
		user_id: 1,
		category: "fruit",
		item_name: "apple",
		item_description: "I have 5 red apples to give",
		use_by_date: "2022-02-22",
		date_added: "2022-02-18",
		quantity: "5 grams",
		cloudinary_id: "",
		item_image:
			"https://upload.wikimedia.org/wikipedia/commons/f/f4/Honeycrisp.jpg",
		is_reserved: false,
		availablity: true,
		time_slot: "between 5pm-7pm",
	},
	{
		user_id: 1,
		category: "vegetable",
		item_name: "carrot",
		item_description: "I have 10kg of carrots to give",
		use_by_date: "2022-02-22",
		date_added: "2022-02-18",
		quantity: "2 bags",
		cloudinary_id: "",
		item_image:
			"https://upload.wikimedia.org/wikipedia/commons/f/f4/Honeycrisp.jpg",
		is_reserved: true,
		availability: false,
		time_slot: "12:00pm-2:00pm",
	},
	{
		user_id: 2,
		category: "fruit",
		item_name: "banana",
		item_description: "I have 7 fresh bananas to give",
		use_by_date: "2022-02-22",
		date_added: "2022-02-18",
		quantity: "2 bunches",
		cloudinary_id: "",
		item_image: "",
		is_reserved: false,
		availablity: true,
		time_slot: "between 2pm-3pm",
	},
	{
		user_id: 2,
		category: "vegetable",
		item_name: "salad",
		item_description: "I have 500g of salad to give away",
		use_by_date: "2022-02-22",
		date_added: "2022-02-18",
		quantity: "1 pack",
		cloudinary_id: "",
		item_image: "",
		is_reserved: true,
		availability: false,
		time_slot: "1:00pm-3:00pm",
	},
	{
		user_id: 2,
		category: "fruit",
		item_name: "kiwi",
		item_description: "I have 6 furry kiwis to give away",
		use_by_date: "2022-02-22",
		date_added: "2022-02-18",
		quantity: "4",
		cloudinary_id: "",
		item_image: "",
		is_reserved: true,
		availability: false,
		time_slot: "12:00pm-2:00pm",
	},
];
